web:
  build: .
  ports:
    - 8080:8080
redis:
  image: redis
  ports:
    - 6379:6379
phantomjs:
  ports:
    - 8910:8910
  image: wernight/phantomjs
  command: "/usr/local/bin/phantomjs --webdriver=8910"
boxel:
  image: boxel-cli
  command: "boxel video -R redis://192.168.99.100:6379/0 -U ws://192.168.99.100:8080/ws"
  links:
    - redis
    - phantomjs
    - web

